In [7]:
import pandas as pd
# Files to load
school_data_to_load = os.path.join("Resources/schools_complete.csv")
student_data_to_load =os.path.join("Resources/students_complete.csv")

NameError: name 'os' is not defined

In [3]:
#read the files using read()
schooldata_df=pd.read_csv(school_data_toload)
schooldata_df

FileNotFoundError: [Errno 2] File Resources\schools_complete.csv does not exist: 'Resources\\schools_complete.csv'

In [5]:
# Read the school data file and store it in a Pandas DataFrame.
school_data_df = pd.read_csv(school_data_toload)
school_data_df

FileNotFoundError: [Errno 2] File Resources\schools_complete.csv does not exist: 'Resources\\schools_complete.csv'

In [9]:
import pandas as pd
import os 
# Files to load
school_data_to_load = os.path.join ("Resources/schools_complete.csv")
student_data_to_load =os.path.join ("Resources/students_complete.csv")

In [15]:
# Read the school data file and store it in a Pandas DataFrame.
school_data_df = pd.read_csv(school_data_to_load)
school_data_df.head()

   School ID            school_name      type  size   budget
0          0      Huang High School  District  2917  1910635
1          1   Figueroa High School  District  2949  1884411
2          2    Shelton High School   Charter  1761  1056600
3          3  Hernandez High School  District  4635  3022020
4          4    Griffin High School   Charter  1468   917500

In [14]:
# Read the student data file and store it in a Pandas DataFrame.
student_data_df = pd.read_csv(student_data_to_load)
student_data_df.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [16]:
# Read the student data file and store it in a Pandas DataFrame.
student_data_df = pd.read_csv(student_data_to_load)
student_data_df.tail()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75